_target_: sandbox.models.adit.ADiTModel
ckpt_path: ./models/adit/checkpoints/adit/ldm.ckpt
autoencoder_ckpt: ./models/adit/checkpoints/adit/vae.ckpt
data: mp20_only
sampling:
  num_samples: 10
  batch_size: 10
