# --- physical constants
NUM_ELEMENTS: int = 98  # atomic numbers above 98 are physically unstable
NUM_SPACE_GROUPS: int = 230
LATTICE_COMPONENTS: int = 6
MAX_WYCKOFF_SITES: int = 27

# --- data constants
EPSILON: float = 1e-6  # for numerical stability
MAX_NEIGHBORS: int = 20

# Stats from train and validation splits TODO: make configurable?
lattice_parameter_ranges = {
    "mp_20": {
        "min_lattice_length": 2.0,  # Angstroms
        "max_lattice_length": 133.0,
        "min_lattice_angle": 60.0,  # Degrees
        "max_lattice_angle": 135.0,
    },
    "mpts_52": {
        "min_lattice_length": 0.98,  # Angstroms
        "max_lattice_length": 189.5,
        "min_lattice_angle": 60.0,  # Degrees
        "max_lattice_angle": 135.0,
    },
}
max_atoms_per_dataset = {
    "mp_20": 20,
    "mpts_52": 52,
}

chemical_symbols = [
    # 0
    "X",
    # 1
    "H",
    "He",
    # 2
    "Li",
    "Be",
    "B",
    "C",
    "N",
    "O",
    "F",
    "Ne",
    # 3
    "Na",
    "Mg",
    "Al",
    "Si",
    "P",
    "S",
    "Cl",
    "Ar",
    # 4
    "K",
    "Ca",
    "Sc",
    "Ti",
    "V",
    "Cr",
    "Mn",
    "Fe",
    "Co",
    "Ni",
    "Cu",
    "Zn",
    "Ga",
    "Ge",
    "As",
    "Se",
    "Br",
    "Kr",
    # 5
    "Rb",
    "Sr",
    "Y",
    "Zr",
    "Nb",
    "Mo",
    "Tc",
    "Ru",
    "Rh",
    "Pd",
    "Ag",
    "Cd",
    "In",
    "Sn",
    "Sb",
    "Te",
    "I",
    "Xe",
    # 6
    "Cs",
    "Ba",
    "La",
    "Ce",
    "Pr",
    "Nd",
    "Pm",
    "Sm",
    "Eu",
    "Gd",
    "Tb",
    "Dy",
    "Ho",
    "Er",
    "Tm",
    "Yb",
    "Lu",
    "Hf",
    "Ta",
    "W",
    "Re",
    "Os",
    "Ir",
    "Pt",
    "Au",
    "Hg",
    "Tl",
    "Pb",
    "Bi",
    "Po",
    "At",
    "Rn",
    # 7
    "Fr",
    "Ra",
    "Ac",
    "Th",
    "Pa",
    "U",
    "Np",
    "Pu",
    "Am",
    "Cm",
    "Bk",
    "Cf",
    "Es",
    "Fm",
    "Md",
    "No",
    "Lr",
    "Rf",
    "Db",
    "Sg",
    "Bh",
    "Hs",
    "Mt",
    "Ds",
    "Rg",
    "Cn",
    "Nh",
    "Fl",
    "Mc",
    "Lv",
    "Ts",
    "Og",
]

# Tensor of unit cells. Assumes 27 cells in -1, 0, 1 offsets in the x and y
# dimensions. Note that differing from OCP, we have 27 offsets here because we
# are in 3D
OFFSET_LIST = [
    [-1, -1, -1],
    [-1, -1, 0],
    [-1, -1, 1],
    [-1, 0, -1],
    [-1, 0, 0],
    [-1, 0, 1],
    [-1, 1, -1],
    [-1, 1, 0],
    [-1, 1, 1],
    [0, -1, -1],
    [0, -1, 0],
    [0, -1, 1],
    [0, 0, -1],
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, -1],
    [0, 1, 0],
    [0, 1, 1],
    [1, -1, -1],
    [1, -1, 0],
    [1, -1, 1],
    [1, 0, -1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, -1],
    [1, 1, 0],
    [1, 1, 1],
]

periodic_table_data = {
    "H": {"computational_atomic_radius": 0.53, "experimental_atomic_radius": 1.1},
    "He": {"computational_atomic_radius": 0.31, "experimental_atomic_radius": 1.4},
    "Li": {"computational_atomic_radius": 1.67, "experimental_atomic_radius": 1.82},
    "Be": {"computational_atomic_radius": 1.12, "experimental_atomic_radius": 1.53},
    "B": {"computational_atomic_radius": 0.87, "experimental_atomic_radius": 1.92},
    "C": {"computational_atomic_radius": 0.67, "experimental_atomic_radius": 1.7},
    "N": {"computational_atomic_radius": 0.56, "experimental_atomic_radius": 1.55},
    "O": {"computational_atomic_radius": 0.48, "experimental_atomic_radius": 1.52},
    "F": {"computational_atomic_radius": 0.42, "experimental_atomic_radius": 1.47},
    "Ne": {"computational_atomic_radius": 0.38, "experimental_atomic_radius": 1.54},
    "Na": {"computational_atomic_radius": 1.9, "experimental_atomic_radius": 2.27},
    "Mg": {"computational_atomic_radius": 1.45, "experimental_atomic_radius": 1.73},
    "Al": {"computational_atomic_radius": 1.18, "experimental_atomic_radius": 1.84},
    "Si": {"computational_atomic_radius": 1.11, "experimental_atomic_radius": 2.1},
    "P": {"computational_atomic_radius": 0.98, "experimental_atomic_radius": 1.8},
    "S": {"computational_atomic_radius": 0.88, "experimental_atomic_radius": 1.8},
    "Cl": {"computational_atomic_radius": 0.79, "experimental_atomic_radius": 1.75},
    "Ar": {"computational_atomic_radius": 0.71, "experimental_atomic_radius": 1.88},
    "K": {"computational_atomic_radius": 2.43, "experimental_atomic_radius": 2.75},
    "Ca": {"computational_atomic_radius": 1.94, "experimental_atomic_radius": 2.31},
    "Sc": {"computational_atomic_radius": 1.84, "experimental_atomic_radius": 2.15},
    "Ti": {"computational_atomic_radius": 1.76, "experimental_atomic_radius": 2.11},
    "V": {"computational_atomic_radius": 1.71, "experimental_atomic_radius": 2.07},
    "Cr": {"computational_atomic_radius": 1.66, "experimental_atomic_radius": 2.06},
    "Mn": {"computational_atomic_radius": 1.61, "experimental_atomic_radius": 2.05},
    "Fe": {"computational_atomic_radius": 1.56, "experimental_atomic_radius": 2.04},
    "Co": {"computational_atomic_radius": 1.52, "experimental_atomic_radius": 2.0},
    "Ni": {"computational_atomic_radius": 1.49, "experimental_atomic_radius": 1.97},
    "Cu": {"computational_atomic_radius": 1.45, "experimental_atomic_radius": 1.96},
    "Zn": {"computational_atomic_radius": 1.42, "experimental_atomic_radius": 2.01},
    "Ga": {"computational_atomic_radius": 1.36, "experimental_atomic_radius": 1.87},
    "Ge": {"computational_atomic_radius": 1.25, "experimental_atomic_radius": 2.11},
    "As": {"computational_atomic_radius": 1.14, "experimental_atomic_radius": 1.85},
    "Se": {"computational_atomic_radius": 1.03, "experimental_atomic_radius": 1.9},
    "Br": {"computational_atomic_radius": 0.94, "experimental_atomic_radius": 1.85},
    "Kr": {"computational_atomic_radius": 0.88, "experimental_atomic_radius": 2.02},
    "Rb": {"computational_atomic_radius": 2.65, "experimental_atomic_radius": 3.03},
    "Sr": {"computational_atomic_radius": 2.19, "experimental_atomic_radius": 2.49},
    "Y": {"computational_atomic_radius": 2.12, "experimental_atomic_radius": 2.32},
    "Zr": {"computational_atomic_radius": 2.06, "experimental_atomic_radius": 2.23},
    "Nb": {"computational_atomic_radius": 1.98, "experimental_atomic_radius": 2.18},
    "Mo": {"computational_atomic_radius": 1.9, "experimental_atomic_radius": 2.17},
    "Tc": {"computational_atomic_radius": 1.83, "experimental_atomic_radius": 2.16},
    "Ru": {"computational_atomic_radius": 1.78, "experimental_atomic_radius": 2.13},
    "Rh": {"computational_atomic_radius": 1.73, "experimental_atomic_radius": 2.1},
    "Pd": {"computational_atomic_radius": 1.69, "experimental_atomic_radius": 2.1},
    "Ag": {"computational_atomic_radius": 1.65, "experimental_atomic_radius": 2.11},
    "Cd": {"computational_atomic_radius": 1.61, "experimental_atomic_radius": 2.18},
    "In": {"computational_atomic_radius": 1.56, "experimental_atomic_radius": 1.93},
    "Sn": {"computational_atomic_radius": 1.45, "experimental_atomic_radius": 2.17},
    "Sb": {"computational_atomic_radius": 1.33, "experimental_atomic_radius": 2.06},
    "Te": {"computational_atomic_radius": 1.23, "experimental_atomic_radius": 2.06},
    "I": {"computational_atomic_radius": 1.15, "experimental_atomic_radius": 1.98},
    "Xe": {"computational_atomic_radius": 1.08, "experimental_atomic_radius": 2.16},
    "Cs": {"computational_atomic_radius": 2.98, "experimental_atomic_radius": 3.43},
    "Ba": {"computational_atomic_radius": 2.53, "experimental_atomic_radius": 2.68},
    "La": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.43},
    "Ce": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.42},
    "Pr": {"computational_atomic_radius": 2.47, "experimental_atomic_radius": 2.4},
    "Nd": {"computational_atomic_radius": 2.06, "experimental_atomic_radius": 2.39},
    "Pm": {"computational_atomic_radius": 2.05, "experimental_atomic_radius": 2.38},
    "Sm": {"computational_atomic_radius": 2.38, "experimental_atomic_radius": 2.36},
    "Eu": {"computational_atomic_radius": 2.31, "experimental_atomic_radius": 2.35},
    "Gd": {"computational_atomic_radius": 2.33, "experimental_atomic_radius": 2.34},
    "Tb": {"computational_atomic_radius": 2.25, "experimental_atomic_radius": 2.33},
    "Dy": {"computational_atomic_radius": 2.28, "experimental_atomic_radius": 2.31},
    "Ho": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.3},
    "Er": {"computational_atomic_radius": 2.26, "experimental_atomic_radius": 2.29},
    "Tm": {"computational_atomic_radius": 2.22, "experimental_atomic_radius": 2.27},
    "Yb": {"computational_atomic_radius": 2.22, "experimental_atomic_radius": 2.26},
    "Lu": {"computational_atomic_radius": 2.17, "experimental_atomic_radius": 2.24},
    "Hf": {"computational_atomic_radius": 2.08, "experimental_atomic_radius": 2.23},
    "Ta": {"computational_atomic_radius": 2.0, "experimental_atomic_radius": 2.22},
    "W": {"computational_atomic_radius": 1.93, "experimental_atomic_radius": 2.18},
    "Re": {"computational_atomic_radius": 1.88, "experimental_atomic_radius": 2.16},
    "Os": {"computational_atomic_radius": 1.85, "experimental_atomic_radius": 2.16},
    "Ir": {"computational_atomic_radius": 1.8, "experimental_atomic_radius": 2.13},
    "Pt": {"computational_atomic_radius": 1.77, "experimental_atomic_radius": 2.13},
    "Au": {"computational_atomic_radius": 1.74, "experimental_atomic_radius": 2.14},
    "Hg": {"computational_atomic_radius": 1.71, "experimental_atomic_radius": 2.23},
    "Tl": {"computational_atomic_radius": 1.56, "experimental_atomic_radius": 1.96},
    "Pb": {"computational_atomic_radius": 1.54, "experimental_atomic_radius": 2.02},
    "Bi": {"computational_atomic_radius": 1.43, "experimental_atomic_radius": 2.07},
    "Po": {"computational_atomic_radius": 1.35, "experimental_atomic_radius": 1.97},
    "At": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.02},
    "Rn": {"computational_atomic_radius": 1.2, "experimental_atomic_radius": 2.2},
    "Fr": {"computational_atomic_radius": None, "experimental_atomic_radius": 3.48},
    "Ra": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.83},
    "Ac": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.47},
    "Th": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.45},
    "Pa": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.1},
    "U": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.41},
    "Np": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.39},
    "Pu": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.43},
    "Am": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.44},
    "Cm": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.45},
    "Bk": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.44},
    "Cf": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.45},
    "Es": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.45},
    "Fm": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.45},
    "Md": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.46},
    "No": {"computational_atomic_radius": None, "experimental_atomic_radius": 2.46},
    "Lr": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Rf": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Db": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Sg": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Bh": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Hs": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Mt": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Ds": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Rg": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Cn": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Nh": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Fl": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Mc": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Lv": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Ts": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
    "Og": {"computational_atomic_radius": None, "experimental_atomic_radius": None},
}
