# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        cp uv.toml.cpu uv.toml
        uv sync --extra dev --extra cdvae --extra research --extra relax
    - name: Test wyckoff-transformer with pytest
      run: |
        uv run pytest --run-relax
    - name: Test cdvae-property-models with pytest
      run: |
        cp uv.toml.cpu cdvae_property_models/uv.toml
        cd cdvae_property_models
        uv run --extra dev pytest